require "user.plugins"
require "user.options"
require "user.web_devicons"
require "user.bufferline"
require "user.statusline"
require "user.nvimtree"
require "user.treesitter"
require "user.toggleterm"
require "user.cmp"
require "user.lsp"
require "user.symbols_outline"
require "user.telescope"
require "colorizer"
-- require "user.web_devicons"
-- require "user.test_toggleterm"
vim.cmd[[colorscheme tokyonight]]

